//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFInterfaceStep
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimioCalculationStepSample2Entities : DbContext
    {
        public SimioCalculationStepSample2Entities()
            : base("name=SimioCalculationStepSample2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<ServerVisit> ServerVisits { get; set; }
        public virtual DbSet<EntityVisit> EntityVisits { get; set; }
    }
}
